language: ruby

sudo: false

rvm: 2.3.1

env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000

cache: bundler

addons:
  postgresql: 9.3

services:
  - redis

before_script:
  - 'RAILS_ENV=test bundle exec rake db:create --trace'
  
  
notifications:
  slack: myown-org:yZs0ajxa6gd7FujkoSV1tOum
  webhooks: 
    urls: 
      -http://myhost254.ddns.net:50500
  on_success: always
  on_failure: always 
  on_start: always 
  on_cancel: always
  on_error: always 
